# Docker compose file to define single host peerbook service
version: '3'
services:
  peerbook:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ENVIRONMENT}/peerbook/server:${HASH}
    ports:
      - "80:17777"
      - "60000-61000:60000-61000/udp"
    environment:
      AWS_REGION: ${AWS_REGION}
      LAYER_NAME: ${LAYER_NAME}
      REDIS_HOST: valkey:6379
      PB_HOME_URL: http://${PUBLIC_IP}
      WEBEXEC_SERVER_URL: http://${PUBLIC_IP}
      WEBRTC_IP_ADDRESS: ${PUBLIC_IP}
        # logging:
        # driver: awslogs
        # options:      
        # awslogs-group: ${LAYER_NAME}-api
        # awslogs-region: ${AWS_REGION}
        # awslogs-stream-prefix: api
  valkey:
    image: valkey/valkey:7.2.5-alpine
    expose:
      - 6379
